- name: Variables Demo Practice
  hosts: localhost
  vars:
    exx: this is charan play.example.com and the website is example website+
  vars_files:
    - vars.yml

  tasks:
    - name: Print URL of example
      ansible.builtin.debug:
        msg: URL of the website is - {{exx}}


    - name: Print fruit names in Aldi
      ansible.builtin.debug:
        msg: Fruit name is - {{Fruit_name}}
      vars:
        Fruit_name: Apple and Banane


    - name: Print User Name we have given
      ansible.builtin.debug:
        msg: Name we have assigned is {{Name}}

