- name: Variables Demo Practice
  hosts: localhost
  vars:
    exx: this is charan play.example.com and the website is example website



  vars_files:
    - vars.yml
    - usernames.yml



  tasks:
    - name: Print URL of example
      ansible.builtin.debug:
        msg: URL of the website is - {{exx}}


    - name: Print fruit names in Aldi
      ansible.builtin.debug:
        msg: Fruit name is - {{Fruit_name}}
      vars:
        Fruit_name: Apple and Banane


    - name: Print the given project name
      ansible.builtin.debug:
        msg: Project Name we have assigned is {{Project_Name}}


    - name: Print the User Name we have given
      ansible.builtin.debug:
        msg: User Name we have assigned is {{User_Name}}


    - name: Print Command Line Input Variable
      ansible.builtin.debug:
        msg: The Course Name we have assigned is {{Course_Name}}




