- name: Variables Demo Practice
  hosts: localhost
  vars:
    exx: play.example.com
  tasks:
    - name: Print URL of example
      ansible.builtin.debug:
        msg: URL of the website is - {{ exx }}

