- name: Variables Demo Practice
  hosts: 172.31.87.168
  vars:
    exx: this is charan play.example.com and the website is example website
  tasks:
    - name: Print URL of example
      ansible.builtin.debug:
        msg: URL of the website is - {{ exx }}

