- name: Conditions explanation
  hosts: localhost
  tasks:
    - name: Welcome to Charan DevOps Course with explanation
      ansible.builtin.debug:
        msg: Welcome to Devops Course
      when: course_name=='Devops' or course_name=='Java'

    - name: Welcome to Charan AWS Course with explanation
      ansible.builtin.debug:
         msg: Welcome to AWS Course
      when: course_name=='AWS'