- name: Conditions explanation
  hosts: localhost
  tasks:
    - name: Welcome to Charan DevOps Course with explanation
      ansible.builtin.debug:
        msg: Welcome to Devops Course

    - name: Welcome to Charan AWS Course with explanation
      ansible.builtin.debug:
         msg: Welcome to AWS Course