- name: loops explanation
  hosts: localhost
  tasks:
    - name: Print Fruit names with the help of loops
      ansible.builtin.debug:
        msg: Fruit Name in sequence is {{item}}
      loop:
        - apple
        - banane
#        - orange
#        - guava
#        - lime
#        - tomato
#        - kaju
#        - pandu

    - name:  Print Course
      ansible.builtin.debug:
        msg: Course name is {{item["course_name"]}}, Trainer name is {{["trainer_name"]}}
      loop:
        - {course_name: Devops, trainer_name: Raju}
        - {course_name: AWS, trainer_name: Naveen}
        - {course_name: Java, trainer_name: }




