- name: loops explanation
  hosts: localhost
  tasks:
    - name: Print Fruit names with the help of loops
      ansible.builtin.debug:
        msg: Fruit Name in sequence is {{i}}
      loop:
        - apple
        - banane
        - orange
        - guava
        - lime
        - tomato
        - kaju
