- name: Setup Facts explanation
  hosts: localhost
  tasks:
    - name: Print ansible architecture kap
      ansible.builtin.debug:
        msg: "{{ansible_architecture}}"

    - name: Print date and time
      ansible.builtin.debug:
        msg: "{{ansible_date_time.day}}"
      register: day

    - name: Print day
      ansible.builtin.debug:
        msg: "{{day}}"