- name: Error Handling
  hosts: localhost
  tasks:
    - name: Check User
      ansible.builtin.shell: id expense
      register: out
      igone_erros: true

    - name: print output
      ansible.builtin.debug:
        msg:"{{out}}"
